name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  IDFY_MOCK_SERVER_VERSION: 0.0.9

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit exists in master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master

      - name: Start mock server
        run: |
          mkdir -p idfy-mock-server/idfy-mock-server_$IDFY_MOCK_SERVER_VERSION/
          curl -L "https://github.com/idfy-io/idfy-mock-server/releases/download/v$IDFY_MOCK_SERVER_VERSION/idfy-mock-server_$IDFY_MOCK_SERVER_VERSION.zip" -o "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip"
          unzip "idfy-mock-server/idfy-mock-server_$IDFY_MOCK_SERVER_VERSION.zip" -d "idfy-mock-server/idfy-mock-server_$IDFY_MOCK_SERVER_VERSION/"
          dotnet "idfy-mock-server/idfy-mock-server_$IDFY_MOCK_SERVER_VERSION/Idfy.MockServer.dll" &

      - name: Build
        run: dotnet build src -c Release

      - name: Test
        run: dotnet test src -c Release --no-build

      - name: Pack
        run: dotnet pack src/Signicat.SDK -c Release -o .

      - name: Push
        run: dotnet nuget push Signicat.SDK.* --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: GitHub Release
        uses: softprops/action-gh-release@v1